# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'KPMG ITS NL Test-Ashwin(206534c0-1c62-4c7d-9f76-2713163b653d)'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'test.azcli'